### ISSUE TITLE
How to Use FlipView

### ISSUE THREAD

**Issue by pallammadhukar** [Kinnara/WPToolkit#13]
Please provide sample code. when using this control it is printing namespace of the data item. In sample it is working fine. but why my code is printing dataitem namespace.

**Comment by Kinnara** [comment]
The sample has sample code.

**Comment by pallammadhukar** [comment]
Please can you help me. i am getting error. 
![error](https://f.cloud.github.com/assets/3232745/2204470/a6329a1c-993d-11e3-8124-fdb42ab73215.png)

**Comment by pallammadhukar** [comment]
i got working after adding "Microsoft.Phone.Controls.dll" from C:\Program Files (x86)\Microsoft SDKs\Windows Phone\v8.0\Libraries

**Comment by pallammadhukar** [comment]
Got another Execption: MS.Internal.WrappedException

Message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Source: System.Windows
Stacktrace:
   at MS.Internal.XcpImports.CheckHResult(UInt32 hr)
   at MS.Internal.XcpImports.UIElement_Measure(UIElement element, Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at Microsoft.Phone.Controls.LongListSelector.RealizeDisplayItem(Iterator`1 iterator, RealizeOptions options)
   at Microsoft.Phone.Controls.LongListSelector.RealizedRange.Append(RealizedRange nextRange, Double bottom)
   at Microsoft.Phone.Controls.LongListSelector.AppendElement(RealizedRange range, RealizedRange nextRange, Double bottom)
   at Microsoft.Phone.Controls.LongListSelector.HealElements(Rect requireRect, Rect allowRect, Boolean& areBoundsUpdated)
   at Microsoft.Phone.Controls.LongListSelector.Balance()
   at Microsoft.Phone.Controls.LongListSelector.MeasureOverride(Size availableSize)
   at System.Windows.FrameworkElement.MeasureOverride(IntPtr nativeTarget, Double inWidth, Double inHeight, Double& outWidth, Double& outHeight)

**Comment by Kinnara** [comment]
If you use NuGet that reference will be automatically added.

**Comment by Kinnara** [comment]
The exception seems to be from LongListSelector, which is not a toolkit control. LongListSelector does have some bugs.
