### ISSUE TITLE
NullReferenceException in TransitionFrame

### ISSUE THREAD

**Issue by Pepsi1x1** [Kinnara/WPToolkit#22]
I'm afraid I don't have repro steps for this, but have received a few crash reports relating to this from a production app.

NullReferenceException
   at Microsoft.Phone.Controls.TransitionFrame.EnsureLastTransitionIsComplete()
   at Microsoft.Phone.Controls.TransitionFrame.OnNavigating(Object sender, NavigatingCancelEventArgs e)
   at System.Windows.Navigation.NavigationService.RaiseNavigating(Uri uri, NavigationMode mode, Boolean isFragmentNavigationOnly, Boolean isCancelable, Boolean isNavigationInitiator, PhoneApplicationPage existingContentPage)
   at System.Windows.Navigation.NavigationService.Journal_NavigatingBack(Object sender, JournalEventArgs args)
   at System.Windows.Navigation.Journal.OnNavigatingBack()
   at System.Windows.Navigation.Journal.ShellPage_BackKeyPressed(Object sender, BackKeyPressEventArgs args)
   at Microsoft.Phone.Shell.Interop.ShellPageCallback.FireOnBackKeyPress(IntPtr pageThis)

**Comment by Kinnara** [comment]
I guess the app uses an older version of the toolkit? I believe this issue has been fixed in b35219710da336e33c0e485b3fd17e7f53eace54.
